name = "myportfolio"
main = "dist/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "dist"

[build]
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20.3.0"

